name: Automatisches Update der Finanzdaten

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Läuft täglich um Mitternacht UTC

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: 🔥 Erstelle `data/` Ordner (Fix für OSError)
        run: mkdir -p data  # Erstellt den `data/` Ordner, falls nicht vorhanden

      - name: Finanzdaten abrufen und speichern
        run: python src/fetch_data.py

      - name: Änderungen committen und pushen
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Verwende das Secret für Authentifizierung
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git add data/*.csv
          git commit -m "Automatisches Update der Finanzdaten"
          git push
