name: Automatisches Update der Finanzdaten

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Läuft täglich um Mitternacht UTC

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: 🔥 Erstelle `data/` Ordner
        run: mkdir -p data  

      - name: Finanzdaten abrufen und speichern
        run: python src/fetch_data.py

      - name: SSH Key einrichten
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git add data/*.csv
          git commit -m "Automatisches Update der Finanzdaten" || echo "Keine neuen Änderungen"
          git push origin main
