name: Automatisches Update der Finanzdaten

on:
  schedule:
    - cron: '0 0 * * *'  # Läuft täglich um Mitternacht (UTC)
  workflow_dispatch:  # Erlaubt manuelles Starten

jobs:
  update_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository klonen
      uses: actions/checkout@v3

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Abhängigkeiten installieren
      run: |
        pip install -r requirements.txt

    - name: Finanzdaten abrufen und speichern
      run: python src/fetch_data.py

    - name: Änderungen committen und pushen
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automatisches Update der Finanzdaten" || echo "Keine Änderungen"
        git push origin main
